name: mineral_ioc
description: Mineral services container
version: 1.0.0

repository: https://github.com/mineral-dart/container
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

platforms:
  linux:
  macos:
  windows:

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
